#ifndef CHALLENGE_SECOND_READER_H_
#define CHALLENGE_SECOND_READER_H_

#define READER_MAX_RANDOM_SEGMENTS 20
#define READER_NUM_BUFFERED_SEGMENTS 5
#define READER_NUM_POOLTHREADS 5

#endif//CHALLENGE_SECOND_READER_H_
